-- MySQL Script generated by MySQL Workbench
-- Tue May  2 23:13:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema mytestschema2
-- -----------------------------------------------------
-- test schema 2

-- -----------------------------------------------------
-- Schema mytestschema2
--
-- test schema 2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mytestschema2` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `mytestschema2` ;

-- -----------------------------------------------------
-- Table `mytestschema2`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mytestschema2`.`student` (
  `student_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `student_name` VARCHAR(45) NOT NULL,
  `student_address` VARCHAR(45) NOT NULL,
  `student_DOB` DATE NULL,
  PRIMARY KEY (`student_id`))
ENGINE = InnoDB
COMMENT = 'maintains the Student details';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
