-- MySQL Script generated by MySQL Workbench
-- Sat May  6 23:00:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MyTestSchema
-- -----------------------------------------------------
-- Schema to be used in Web appication project (ProjWebApp1)

-- -----------------------------------------------------
-- Schema MyTestSchema
--
-- Schema to be used in Web appication project (ProjWebApp1)
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyTestSchema` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `MyTestSchema` ;

-- -----------------------------------------------------
-- Table `MyTestSchema`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MyTestSchema`.`customer` (
  `cust_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `cust_name` VARCHAR(45) NOT NULL,
  `cust_address` VARCHAR(45) NOT NULL,
  `cust_email` VARCHAR(45) NOT NULL,
  `cust_DateOfBirth` DATE NULL,
  `cust_DateOfRegistration` DATETIME NOT NULL,
  PRIMARY KEY (`cust_id`))
ENGINE = InnoDB
COMMENT = 'maintains customer details';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
